nfs:
  server: "192.168.1.100"
  path: "/mnt/hdd"

storageClass:
  default: true
  reclaimPolicy: Retain

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - k8s-node-3
