apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloudpv
  labels:
    app: owncloud
spec:
  storageClassName: "local-path"
  capacity:
    storage: 800Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/hdd/owncloud-owncloudpvc-pvc-ec8c4a5a-160e-4803-b593-5a0217b86ee2
    server: 192.168.1.100
