apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadbpvc
  namespace: owncloud
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: "mariadbpv"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadbpv
  labels:
    app: owncloud
spec:
  storageClassName: "local-path"
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/hdd/owncloud-mariadbpvc-pvc-10cd1bbb-91f5-49ac-8d8b-47d964711bde
    server: 192.168.1.100
